/*USE scubashop;
GO
ALTER TABLE Products WITH CHECK
ADD CONSTRAINT FK_CategoryID FOREIGN KEY(CategoryID) REFERENCES Category(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_PaymentID FOREIGN KEY(PaymentID) REFERENCES Payment(ID)
ON UPDATE CASCADE
GO;
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY(EmployeeID) REFERENCES Employees(ID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetails WITH CHECK
ADD CONSTRAINT FK_OrderID FOREIGN KEY(OrderID) REFERENCES Orders(ID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetails WITH CHECK
ADD CONSTRAINT FK_InventoryID FOREIGN KEY (InventoryID) REFERENCES Products(ProductID)
ON UPDATE CASCADE
GO*/


